services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_mascarade
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: mascarade
    ports:
      - 5434:5432
    volumes:
      - /var/lib/postgresql/data
  mongo:
    image: mongo:6.0
    container_name: mongo_mascarade
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - 27019:27017
    volumes:
      - /var/lib/mongodb/data

